services:
  postgres:
    image: postgres:16-alpine
    container_name: payments_system-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: payments_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  keycloak-db:
    image: postgres:16-alpine
    container_name: keycloak-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    ports:
      - "5433:5432"
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    depends_on:
      - keycloak-db
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    command: [ "start-dev", "--import-realm" ]
    volumes:
      - ./keycloak:/opt/keycloak/data/import
      - ./keycloak/themes:/opt/keycloak/themes

  keycloak-config:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak-config
    depends_on:
      - keycloak
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        until /opt/keycloak/bin/kcadm.sh config credentials \
          --server http://keycloak:8080 \
          --realm master \
          --user admin \
          --password admin; do
          sleep 2
        done
        /opt/keycloak/bin/kcadm.sh update realms/psproject \
          -s loginTheme=payflow \
          -s internationalizationEnabled=true \
          -s 'supportedLocales=["ru","en"]' \
          -s defaultLocale=ru \
          -s registrationEmailAsUsername=true
    restart: "no"

  redis:
    image: redis:7-alpine
    container_name: payment-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  keycloak_postgres_data:
  postgres_data:
  redis_data:
