keycloak:
  base-url: ${KEYCLOAK_BASE_URL:http://keycloak:8080}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/psproject}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/psproject/protocol/openid-connect/certs}

  data:
    redis:
      host: redis
      port: 6379

  datasource:
    url: jdbc:postgresql://postgres:5432/payments_system

  kafka:
    bootstrap-servers: kafka:29092
