global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'java'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 'ps_core:8080'
          - 'ps-transfer:8082'
          - 'bff:9091'
          - 'notification-service:8083'

  - job_name: 'ps_core'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['ps_core:8080']

  - job_name: 'ps-transfer'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['ps-transfer:8082']

  - job_name: 'bff'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['bff:9091']

  - job_name: 'notification-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['notification-service:8083']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'ps_core'
          database: 'payments_system'
      - targets: ['transfer-postgres-exporter:9187']
        labels:
          service: 'ps-transfer'
          database: 'ps_transfer'

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
